# エンドポイントの情報が不正確な場合のシナリオ

join_error_scenario = {
    0: {
        "user_name": "",
        "uri": "ws://127.0.0.1:8000/ws/create/?USER_NAME=",
        "command": {},
        "request_status_code": "S121",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    1: {
        "user_name": "fagi",
        "uri": "ws://127.0.0.1:8000/ws/create/?USER_NAME=fagi",
        "command": {},
        "request_status_code": "S221",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    2: {
        "user_name": "user1",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=&USER_NAME=ui",
        "command": {},
        "request_status_code": "S122",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    3: {
        "user_name": "user2",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=99999&USER_NAME=",
        "command": {},
        "request_status_code": "S122",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    4: {
        "user_name": "user3",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=&USER_NAME=",
        "command": {},
        "request_status_code": "S122",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    6: {
        "user_name": "user5",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=11111&USER_NAME=user4",
        "command": {},
        "request_status_code": "S124",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    7: {
        "user_name": "user6",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=99999&USER_NAME=fagi",
        "command": {},
        "request_status_code": "S125",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
}
