# 村人陣営勝利シナリオ

win_villager_scenario = {
    0: {
        "user_name": "fagi",
        "uri": "ws://127.0.0.1:8000/ws/create/?USER_NAME=fagi",
        "command": {},
        "request_status_code": "S221",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    1: {
        "user_name": "ui",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=99999&USER_NAME=ui",
        "command": {},
        "request_status_code": "S222",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    2: {
        "user_name": "198",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=99999&USER_NAME=198",
        "command": {},
        "request_status_code": "S222",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    3: {
        "user_name": "mira",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=99999&USER_NAME=mira",
        "command": {},
        "request_status_code": "S222",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    4: {
        "user_name": "cookie",
        "uri": "ws://127.0.0.1:8000/ws/join/?ROOM_CODE=99999&USER_NAME=cookie",
        "command": {},
        "request_status_code": "S222",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    5: {
        "user_name": "fagi",
        "uri": "",
        "command": {"UPDATE": {"ROOM": {"ROOM_DISCUSSION_TIME": 2}}},
        "request_status_code": "S211",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    6: {
        "user_name": "fagi",
        "uri": "",
        "command": {"EVENT": "OMAKASE_BUTTON"},
        "request_status_code": "S231",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    7: {
        "user_name": "fagi",
        "uri": "",
        "command": {"EVENT": "START_BUTTON"},
        "request_status_code": "S232",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    7.1: {
        "user_name": "fagi",
        "uri": "",
        "command": {"MANAGE": {}},
        "request_status_code": "S290",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    8: {
        "user_name": "fagi",
        "uri": "",
        "command": {},
        "request_status_code": "S233",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    9: {
        "user_name": "fagi",
        "uri": "",
        "command": {"UPDATE": {"ROLE": {"FORTUNE_TELL": 202}}},
        "request_status_code": "S243",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    10: {
        "user_name": "mira",
        "uri": "",
        "command": {"UPDATE": {"ROLE": {"THIEF": 999}}},
        "request_status_code": "S244",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    10.1: {
        "user_name": "fagi",
        "uri": "",
        "command": {},
        "request_status_code": "S234",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    11: {
        "user_name": "fagi",
        "uri": "",
        "command": {"VOTE": {"USER_ID": 202}},
        "request_status_code": "S251",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    12: {
        "user_name": "ui",
        "uri": "",
        "command": {"VOTE": {"USER_ID": 202}},
        "request_status_code": "S251",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    13: {
        "user_name": "198",
        "uri": "",
        "command": {"VOTE": {"USER_ID": 202}},
        "request_status_code": "S251",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    14: {
        "user_name": "mira",
        "uri": "",
        "command": {"VOTE": {"USER_ID": 202}},
        "request_status_code": "S251",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    15: {
        "user_name": "cookie",
        "uri": "",
        "command": {"VOTE": {"USER_ID": 201}},
        "request_status_code": "S251",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    16: {
        "user_name": "fagi",
        "uri": "",
        "command": {},
        "request_status_code": "S252",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    17: {
        "user_name": "fagi",
        "uri": "",
        "command": {},
        "request_status_code": "S261",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    18: {
        "user_name": "ui",
        "uri": "",
        "command": {},
        "request_status_code": "S261",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
    19: {
        "user_name": "198",
        "uri": "",
        "command": {},
        "request_status_code": "S261",
        "wait_time": 0,
        "command_sended": False,
        "response_displayed": False,
    },
}
